version: '3.8'
services:
  agendamedik-api:
    build:
      context: .
      dockerfile: build/Dockerfile.testing
    image: 'agendamedik-api'
    user: 'root'
    command: npm run start:devWin
    environment:
      - NODE_ENV=development
      - PORT=4000
      - BD_SERVER=bx8awnh5ce.database.windows.net
      - DB_USERNAME=desarrollonk@bx8awnh5ce
      - DB_PASSWORD=(n3tm3d1k)
      - DB_NAME_STAGING=netmedik
    ports:
      - 4000:4000
    volumes:
      - ${PWD}:/home/node/app
      - /home/node/app/node_modules
