version: "3.8"
services:

  agendamedik-api:
    build: 
      context: .
      dockerfile: build/production.Dockerfile
    image: "agendamedik-api"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - BD_SERVER=bx8awnh5ce.database.windows.net
      - DB_USERNAME=desarrollonk@bx8awnh5ce
      - DB_PASSWORD=(n3tm3d1k)
      - DB_NAME_STAGING=netmedik
    ports:
      - 4000:3000
